import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Toaster } from "sonner";
import ReduxProviderWrapper from "../components/layout/ReduxProviderWrapper";
import AuthLoader from "../components/layout/AuthLoader";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Pharma Trust",
    description: "Generated by create next app",
    icons: {
        icon: '/l.png',
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <ReduxProviderWrapper>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="light"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <AuthLoader/>
                        {children}
                    </ThemeProvider>
                    <Toaster richColors />
                </ReduxProviderWrapper>
            </body>
        </html>
    );
}
